### ISSUE TITLE
Manifest v3

### ISSUE THREAD

**Issue by sekercancepni** [abhijithvijayan/web-extension-starter#103] opened 2024-01-30 11:46 UTC
Chrome extension no longer supports v2 manifest. Will you update boilerplate to v3?

**Comment by abhijithvijayan-kubric** [comment] 2024-01-30 16:15
yeah will do that today

**Comment by abhijithvijayan** [comment] 2024-01-30 22:54
closing as duplicate of #66

**Closed as completed by abhijithvijayan** 2024-01-30 22:54 UTC
